fix paths for ls and add err handler

diff --git a/install_deploy_tools b/install_deploy_tools
--- a/install_deploy_tools
+++ b/install_deploy_tools
@@ -6,14 +6,16 @@ function handle_exit () {
     echo "Done"
 }
 
+
+function handle_exit () {
+    echo >&2 "Script ERROR detected "
+    exit 1;
+}
+
 #trap "handle_exit" EXIT
-#trap "handle_exit" ERR
+trap "handle_err" ERR
 
 function usage() {
-    if [ "$1" ]; then
-        echo "Error: $1"
-        echo ""
-    fi
     echo ""
     echo "USAGE:"
     echo "        install_from_sinopia [-htdDr] SEMVER"
@@ -32,10 +34,10 @@ function usage() {
     echo "        The final installation directory will use the actual version downloaded"
     echo "        If that version has previously been downloaded, it will not be replaced without supplying -f"
     echo ""
-    if [ $sourced ]; then
-        echo "Sourced"
-        return;
-    else 
+
+    if [ "$1" ]; then
+        echo "Error: $1"
+        echo ""
         exit 1;
     fi
 }
@@ -139,8 +141,8 @@ popd > /dev/null
 #if it doesnt exist already or -f (force) supplied, renaming it to the version that was actually downloaded 
 if [ -d "$base_dir/$installed_version" ]; then
   [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version"
-  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/@mol-platform/deploy_tools/profile"
-  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/@mol-platform/deploy_tools"
+  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/node_modules/@mol-platform/deploy_tools/profile"
+  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/node_modules/@mol-platform/deploy_tools"
         
   # if empty or force_deploy set..        
   if [ ! -e $base_dir/$installed_version/dt/profile ] || [ $force_deploy ]; then
